### ISSUE TITLE
TypeError: Cannot read property 'userId' of null

### ISSUE THREAD

**Issue by uma-08** [davehowson/chat-app#21]
do you got any idea on this error?
(Error in ChatBox.js)
<img width="1236" alt="Screenshot 2021-02-21 at 11 14 36 PM" src="https://user-images.githubusercontent.com/43182226/108633524-a3fd3c80-749a-11eb-8f10-f817a4881ec5.png">

**Comment by UtkarshA135** [comment]
your mongoose model query function Users.find() gives you an array of objects So if you want to Access it the way you have used try like this

Users.findOne({userid:xxx},callback);
or you have to access the array index if you use it find() method

Users.find({userId:xxx},(users)=>{users[0]==neededId}
